import { c as create_ssr_component, h as add_attribute, e as escape, f as each } from "../../../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  let { form } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
  if ($$props.form === void 0 && $$bindings.form && form !== void 0) $$bindings.form(form);
  return `${$$result.head += `<!-- HEAD_svelte-6ycw4p_START -->${$$result.title = `<title>Submit a Deal — TechDeels</title>`, ""}<!-- HEAD_svelte-6ycw4p_END -->`, ""} <div class="max-w-2xl mx-auto px-4 py-8"><div class="bg-white rounded-2xl shadow-sm border border-gray-200 p-8"><h1 class="text-2xl font-bold text-gray-900 mb-2" data-svelte-h="svelte-7uzri4">Submit a Deal</h1> <p class="text-gray-500 text-sm mb-8" data-svelte-h="svelte-fw7dn">Share a great tech deal with the community</p> <form method="POST" class="space-y-6"><div><label for="title" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-1ryhb09">Deal Title *</label> <input type="text" id="title" name="title"${add_attribute("value", form?.title ?? "", 0)} class="${"w-full rounded-lg border " + escape(
    form?.errors?.title ? "border-red-400 bg-red-50" : "border-gray-300",
    true
  ) + " px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent"}" placeholder="e.g. NVIDIA RTX 4070 for $499 at Newegg"> ${form?.errors?.title ? `<p class="text-red-500 text-xs mt-1">${escape(form.errors.title)}</p>` : ``}</div> <div><label for="url" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-1sw3hgv">Deal URL *</label> <input type="url" id="url" name="url"${add_attribute("value", form?.url ?? "", 0)} class="${"w-full rounded-lg border " + escape(
    form?.errors?.url ? "border-red-400 bg-red-50" : "border-gray-300",
    true
  ) + " px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent"}" placeholder="https://www.newegg.com/..."> ${form?.errors?.url ? `<p class="text-red-500 text-xs mt-1">${escape(form.errors.url)}</p>` : ``}</div> <div class="grid grid-cols-2 gap-4"><div><label for="price" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-pitrh6">Deal Price ($)</label> <input type="number" id="price" name="price"${add_attribute("value", form?.price ?? "", 0)} min="0" step="0.01" class="${"w-full rounded-lg border " + escape(
    form?.errors?.price ? "border-red-400 bg-red-50" : "border-gray-300",
    true
  ) + " px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent"}" placeholder="499.99"> ${form?.errors?.price ? `<p class="text-red-500 text-xs mt-1">${escape(form.errors.price)}</p>` : ``}</div> <div><label for="original_price" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-1h7apdd">Original Price ($)</label> <input type="number" id="original_price" name="original_price"${add_attribute("value", form?.original_price ?? "", 0)} min="0" step="0.01" class="${"w-full rounded-lg border " + escape(
    form?.errors?.original_price ? "border-red-400 bg-red-50" : "border-gray-300",
    true
  ) + " px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent"}" placeholder="799.99"></div></div> <div><label for="store" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-10tyas5">Store</label> <input type="text" id="store" name="store"${add_attribute("value", form?.store ?? "", 0)} class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent" placeholder="e.g. Amazon, Newegg, Best Buy"></div> <div><label for="category_id" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-xnigpp">Category</label> <select id="category_id" name="category_id" class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent"><option value="" data-svelte-h="svelte-xy5cex">Select a category...</option>${each(data.categories, (cat) => {
    return `<option${add_attribute("value", cat.id, 0)} ${form?.category_id === cat.id ? "selected" : ""}>${escape(cat.name)}</option>`;
  })}</select></div> <div><label for="description" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-f30id9">Description</label> <textarea id="description" name="description" rows="4" class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent resize-none" placeholder="Add any additional details about this deal...">${escape(form?.description ?? "", false)}</textarea></div> <div><label for="image_url" class="block text-sm font-medium text-gray-700 mb-1" data-svelte-h="svelte-1i3078r">Image URL (optional)</label> <input type="url" id="image_url" name="image_url"${add_attribute("value", form?.image_url ?? "", 0)} class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 focus:border-transparent" placeholder="https://..."></div> <div class="flex gap-3 pt-2"><a href="/" class="flex-1 text-center py-2.5 rounded-lg border border-gray-300 text-gray-700 text-sm font-medium hover:bg-gray-50 transition-colors" data-svelte-h="svelte-49y445">Cancel</a> <button type="submit" class="flex-1 bg-amber-500 hover:bg-amber-400 text-white font-semibold py-2.5 rounded-lg transition-colors shadow-sm" data-svelte-h="svelte-z1zxh5">Submit Deal</button></div></form></div></div>`;
});
export {
  Page as default
};
