import { c as create_ssr_component, e as escape, f as each } from "../../../../chunks/ssr.js";
import { t as timeAgo, f as formatPrice } from "../../../../chunks/utils2.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { data } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
  return `${$$result.head += `<!-- HEAD_svelte-1auexhu_START -->${$$result.title = `<title>${escape(data.profile.username)}&#39;s Profile — TechDeels</title>`, ""}<!-- HEAD_svelte-1auexhu_END -->`, ""} <div class="max-w-4xl mx-auto px-4 py-8"> <div class="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 mb-6"><div class="flex items-center gap-5"><div class="w-16 h-16 rounded-full bg-amber-500 flex items-center justify-center text-white font-bold text-2xl">${escape(data.profile.username[0].toUpperCase())}</div> <div><h1 class="text-2xl font-bold text-gray-900">${escape(data.profile.username)}</h1> <div class="flex items-center gap-3 mt-1">${data.profile.role === "admin" ? `<span class="text-xs bg-red-100 text-red-700 px-2 py-0.5 rounded-full font-medium" data-svelte-h="svelte-11i81ld">Admin</span>` : ``} ${data.profile.created_at ? `<span class="text-sm text-gray-500">Joined ${escape(timeAgo(new Date(data.profile.created_at)))}</span>` : ``}</div></div></div>  <div class="grid grid-cols-3 gap-4 mt-6 pt-6 border-t border-gray-100"><div class="text-center"><div class="text-2xl font-bold text-gray-900">${escape(data.stats.dealCount)}</div> <div class="text-sm text-gray-500 mt-1" data-svelte-h="svelte-xab45f">Deals Submitted</div></div> <div class="text-center"><div class="text-2xl font-bold text-amber-600">${escape(data.stats.totalScore)}</div> <div class="text-sm text-gray-500 mt-1" data-svelte-h="svelte-rsri45">Total Score</div></div> <div class="text-center"><div class="text-2xl font-bold text-green-600">${escape(data.profile.reputation ?? 0)}</div> <div class="text-sm text-gray-500 mt-1" data-svelte-h="svelte-vajius">Reputation</div></div></div></div>  <h2 class="font-bold text-lg text-gray-900 mb-4" data-svelte-h="svelte-10dtale">Submitted Deals</h2> ${data.deals.length === 0 ? `<div class="bg-white rounded-xl border border-gray-200 p-8 text-center"><p class="text-gray-500" data-svelte-h="svelte-wpm7cr">No deals submitted yet.</p></div>` : `<div class="space-y-3">${each(data.deals, (deal) => {
    return `<div class="bg-white rounded-xl border border-gray-200 shadow-sm p-4 flex items-center gap-4"><span class="${"font-bold text-lg w-10 text-center " + escape(
      (deal.score ?? 0) > 0 ? "text-amber-600" : (deal.score ?? 0) < 0 ? "text-red-500" : "text-gray-600",
      true
    )}">${escape(deal.score ?? 0)}</span> <div class="flex-1 min-w-0"><a href="${"/deals/" + escape(deal.id, true)}" class="font-semibold text-gray-900 hover:text-amber-600 transition-colors">${escape(deal.title)}</a> <div class="flex items-center gap-3 mt-0.5 text-sm text-gray-500">${deal.price !== null ? `<span class="text-green-600 font-medium">${escape(formatPrice(deal.price))}</span>` : ``} ${deal.store ? `<span>${escape(deal.store)}</span>` : ``} ${deal.created_at ? `<span class="ml-auto text-xs">${escape(timeAgo(new Date(deal.created_at)))}</span>` : ``} </div></div> ${deal.status === "expired" ? `<span class="text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded-full" data-svelte-h="svelte-fk4c7x">Expired</span>` : ``} </div>`;
  })}</div>`}</div>`;
});
export {
  Page as default
};
